# Generated by Django 4.1.3 on 2023-05-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='locatiom',
            new_name='location',
        ),
    ]
